plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.23'
}

version = mod_version
group = maven_group

base {
    archivesName = archives_base_name
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        remote {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        mavenLocal()
    }
}
